export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_COMPLETE = 'GET_CATEGORIES_COMPLETE';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_CATEGORY_DETAILS_REQUEST = 'GET_CATEGORY_DETAILS_REQUEST';
export const GET_CATEGORY_DETAILS_COMPLETE = 'GET_CATEGORY_DETAILS_COMPLETE';
export const GET_CATEGORY_DETAILS_ERROR = 'GET_CATEGORY_DETAILS_ERROR';

export const GET_ITEM_DETAILS_REQUEST = 'GET_ITEM_DETAILS_REQUEST';
export const GET_ITEM_DETAILS_COMPLETE = 'GET_ITEM_DETAILS_COMPLETE';
export const GET_ITEM_DETAILS_ERROR = 'GET_ITEM_DETAILS_ERROR';

export const GET_LATEST_ITEMS_REQUEST = 'GET_LATEST_ITEMS_REQUEST';
export const GET_LATEST_ITEMS_COMPLETE = 'GET_LATEST_ITEMS_COMPLETE';
export const GET_LATEST_ITEMS_ERROR = 'GET_LATEST_ITEMS_ERROR';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_COMPLETE = 'ADD_ITEM_COMPLETE';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_COMPLETE = 'UPDATE_ITEM_COMPLETE';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_COMPLETE = 'DELETE_ITEM_COMPLETE';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export const G_CONNECT_REQUEST = 'G_CONNECT_REQUEST';
export const G_CONNECT_COMPLETE = 'G_CONNECT_COMPLETE';
export const G_CONNECT_ERROR = 'G_CONNECT_ERROR';

export const LOG_OUT = 'LOG_OUT';